### ISSUE TITLE
[0.95.7 x64] (IRC / tabsrmm group chat) italics text style doesn't work

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1030]
### Expected behavior
When using IRC, basic text styles such as bold, cursive and underlined should work.

### Actual behavior
Miranda can read bold and underlined text. It cannot read italics.
Miranda can't write bold, underlined or italics.
The input box sometimes adds extra tab or space characters that are not there after sending.

### Does it work in stable version?
No, it works neither in stable 0.95.7 nor in the nightly 0.95.7 with the IRC colors fix.

### Steps to reproduce that behavior
Get on IRC with Miranda 0.95.7 and a text style capable test client such as HexChat. Have HexChat output a range of possible combinations between normal, bold, cursive and underlined text.

**Comment by georgehazan** [comment]
cursive - you meant italics? :) hopefully you don't wanna curse it

**Comment by Tharn** [comment]
Yeah I meant italics. Even putting Ctrl-i in Miranda's input box (in IRC) will do something strange, adding an empty tab space and writing italics in the box - but then outputting regular text with an empty space in front.

**Comment by Tharn** [comment]
Just tried the latest nightly which includes this fix (I assume, since Miranda outputs differently).
However, instead of writing italics it looks like it inverts colours.
It also still can't display italics sent from other clients.

![untitled](https://user-images.githubusercontent.com/13466852/32821342-15b34fde-c9d3-11e7-955d-566c9e374e52.png)

**Comment by georgehazan** [comment]
also fixed. there was some strange code

**Comment by Tharn** [comment]
Reading and writing text styles works now. Thank you very much for the fast fixes.

One quirk remains: When using Ctrl-i with the input box, Miranda adds a tab space that it also writes into the message log. The other two clients do not read this space. (I don't know why mIRC does not read spaces at all and HexChat does. Assume other IRC clients are not perfect. I know Pidgin threw a fit trying to read text styles also) Here is a test pattern with numbers separated by Ctrl-i.

![untitled](https://user-images.githubusercontent.com/13466852/32864203-71d4e7c4-ca5e-11e7-9f3b-ef07e7744ab7.png)

**Comment by Tharn** [comment]
It also looks like one of these changes related to text styles & colours broke the /me command. Possibly others, I don't know all of the / commands Miranda supports.

**Comment by georgehazan** [comment]
/me isn't a command, it's a built-in macro. yes, it seems to be broken

**Comment by Tharn** [comment]
It looks like any / commands in the server window are not recognized anymore either. It just tells me 'No such nick/channel'

**Comment by georgehazan** [comment]
fixed /me and all another commands

**Comment by Tharn** [comment]
https://github.com/miranda-ng/miranda-ng/issues/1030#issuecomment-344753667 Is still an issue, even if it is a fairly unimportant one. Everything else is fixed.

**Comment by georgehazan** [comment]
yup, cause Ctrl+I has the code of 0x09 = '\t'...
dunno why the same keystroke is processed twice
