### ISSUE TITLE
ICQ: Messages sent into offline are not received

### ISSUE THREAD

**Issue by thedarkone** [miranda-ng/miranda-ng#1364]
### Expected behavior
A contact sends me an ICQ message while I'm offline (Miranda not running).
I turn on Miranda and the message arrives.

### Actual behavior
I turn on Miranda and the message (that was sent to me while I was offline) does not appear.

### Does it work in stable version?
No

### Steps to reproduce that behavior
 * Shutdown my Miranda client.
 * An ICQ contact sends me a mesage: "Hi, test msg".
 * Start Miranda client, check that message "Hi, test msg" has not been delivered to me.
 * Doesn't work in "Stable version (0.95.8)" nor "Development version (0.95.9)".

----

Official clients (Mac, Web-ICQ etc.) still work as expected and the messages sent while I'm offline are delivered and are visible.

----

Previously, I had a similar issue in the fall of 2017, the fix that worked is described here: https://forum.miranda-ng.org/index.php?topic=5367.0 (clearing Session list on icq.com).

Now clearing all active sessions on https://icq.com/session/list/en no longer helps.

**Comment by RathaWynter** [comment]
Do we know when the change happened that caused ICQ to drop offline messaging support for unofficial clients? This might explain why some of my friends have not been responding to the messages that i've been sending lately. Today (2018-05-17) was when I first tested and confirmed that I couldnt receive them, but would like to know how long its been going on so i can go back and re-send messages.

**Comment by dartraiden** [comment]
First reports from May 15-16.

**Comment by RathaWynter** [comment]
Offline messaging support for ICQ seems to have been fixed server side. Please confirm?
Tested send/receive between Miranda 0.95.8.19890 and Trillian 5.4 Build 16 (April 2014). Both working.
Tested send/receive between Miranda 0.95.8.19890 and 2014-era Miranda NG. Both working.

**Comment by dartraiden** [comment]
Confirmed.

**Comment by homo-programmatis** [comment]
Still happens. Messages sent to Miranda NG when it's offline are never delivered.

**Comment by dartraiden** [comment]
Please. close all open sessions
https://wiki.miranda-ng.org/index.php?title=Plugin:ICQ#Contacts_are_always_online_.2F_not_receiving_.22offline_messages.22

**Comment by homo-programmatis** [comment]
Thanks, that worked!
