### ISSUE TITLE
[dbx_sqlite] only the first of unread events is shown when multiple unread events arrive

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1985]
### Expected behavior
When someone sends me several messages, I expect to open and see all of them when I click the tray icon notification

### Actual behavior
Only the first message is shown in the chat window. When I reopen the chat window, the next unseen message is shown. And again, until all of the messages are shown.

If the window remains opened, messages are shown properly at all times.

### Does it work in stable version?
It works with dbx_mdbx

### Steps to reproduce that behavior
 * have someone send you multiple messages, but do not have the chat window open
 * open the chat window by clicking the tray notification
 * you will only see one message
 * close and reopen the window, you will see another message.

Miranda version 339c8817ec

**Comment by LittleVulpix** [comment]
Still the case with latest dbx_sqlite as of 8.11.2019

**Comment by sss123next** [comment]
fixed in 1198e47c25e12a4743b97674f254f13c6bc0bead

**Comment by LittleVulpix** [comment]
I wanted to try it, however, when I tried to import my mdbx profile into sqlite, it import said "Error loading source file, exiting".

**Comment by LittleVulpix** [comment]
@sss123next thanks, this part is now working correctly; all the pending events are shown. So only #2121 is still not working...
