### ISSUE TITLE
Tox: libtox Crash on .tox profile import in account manager.

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#773]
Tox: Crash on .tox profile import in account manager.

Crashlog+visual studio logs:
[Tox_import-tox-profile_20170321.zip](https://github.com/miranda-ng/miranda-ng/files/1033892/Tox_import-tox-profile_20170321.zip)

Необработанное исключение в "0x13d793dd (libtox.dll)" в "Miranda32.exe": 0xC0000005: Нарушение прав доступа при чтении "0x00000008".

Потоки:

```
Без отметки	>	4052	0	Основной поток	Основной поток	CCtrlButton::OnCommand	Средний
Без отметки		3416	0	Поток рабочего процесса	forkthread_r	mir_sleep	Средний
Без отметки		436	0	Поток рабочего процесса	forkthread_r	ConsoleThread	Средний
Без отметки		1224	0	Поток рабочего процесса	BackgroundThreadProc	_KiFastSystemCallRet@0	Средний
Без отметки		4000	0	Поток рабочего процесса	forkthreadex_r	PopupThread	Средний
Без отметки		2480	0	Поток рабочего процесса	forkthreadex_r	ICQWaitForSingleObject	Средний
Без отметки		2880	0	Поток рабочего процесса	forkthreadex_r	CJabberIqManager::ExpirerThread	Средний
Без отметки		1168	0	Поток рабочего процесса	forkthreadex_r	CJabberProto::ConsoleThread	Средний
Без отметки		2396	0	Поток рабочего процесса	forkthreadex_r	CJabberIqManager::ExpirerThread	Средний
Без отметки		2084	0	Поток рабочего процесса	forkthreadex_r	CJabberProto::ConsoleThread	Средний
Без отметки		2852	0	Поток рабочего процесса	forkthreadex_r	CMraProto::MraAvatarsThreadProc	Средний
Без отметки		2732	0	Поток рабочего процесса	forkthreadex_r	CMsnProto::MSN_AvatarsThread	Средний
Без отметки		2796	0	Поток рабочего процесса	forkthread_r	PicLoader	Бездействие
Без отметки		2336	0	Поток рабочего процесса	forkthread_r	TrayAnimThread	Средний
Без отметки		2688	0	Поток рабочего процесса	forkthread_r	compactHeapsThread	Средний
Без отметки		2600	0	Поток рабочего процесса	forkthreadex_r	Netlib_Select	Средний
Без отметки		1432	0	Поток рабочего процесса	forkthreadex_r	Netlib_Select	Средний
Без отметки		1992	0	Поток рабочего процесса	forkthreadex_r	CVkProto::WorkerThread	Средний
Без отметки		1092	0	Поток рабочего процесса	_SockAsyncThread@4	_KiFastSystemCallRet@0	Выше среднего
Без отметки		3576	0	Поток рабочего процесса	forkthreadex_r	WaitUntilReadable	Средний
Без отметки		1860	0	Поток рабочего процесса	forkthreadex_r	FacebookProto::UpdateLoop	Средний
Без отметки		3348	0	Поток рабочего процесса	forkthreadex_r	WaitUntilReadable	Средний
Без отметки		2560	0	Поток рабочего процесса	_WmipEventPump@4	_KiFastSystemCallRet@0	Средний
Без отметки		2992	0	Поток рабочего процесса	_RtlpTimerThread@4	_KiFastSystemCallRet@0	Средний
Без отметки		3852	0	Поток рабочего процесса	_RtlpWorkerThread@4	_KiFastSystemCallRet@0	Средний
Без отметки		3812	0	Поток рабочего процесса	_RtlpWorkerThread@4	_KiFastSystemCallRet@0	Средний
```

Стек:
```
>	libtox.dll!DllMainCRTStartup()  + 0x17fdd байт	C++
 	mir_core.mir!CCtrlButton::OnCommand(HWND__ * __formal, HWND__ * __formal, unsigned short idCode)  Строка 788	C++
 	mir_core.mir!CDlgBase::DlgProc(unsigned int msg, unsigned int wParam, long lParam)  Строка 171	C++
 	mir_app.mir!CProtoIntDlgBase::DlgProc(unsigned int msg, unsigned int wParam, long lParam)  Строка 123	C++
 	mir_core.mir!CDlgBase::GlobalDlgProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam)  Строка 288 + 0x16 байт	C++
 	user32.dll!_InternalCallWinProc@20()  + 0x28 байт	
 	user32.dll!_UserCallDlgProcCheckWow@32()  + 0xb5 байт	
 	user32.dll!_DefDlgProcWorker@20()  + 0x7f байт	
 	user32.dll!_DefDlgProcW@16()  + 0x22 байт	
 	user32.dll!_InternalCallWinProc@20()  + 0x28 байт	
 	user32.dll!_UserCallWinProcCheckWow@32()  + 0xb7 байт	
 	user32.dll!_SendMessageWorker@20()  + 0xc8 байт	
 	user32.dll!_SendMessageW@16()  + 0x49 байт	
 	comctl32.dll!_Button_NotifyParent@8()  + 0x3d байт	
 	comctl32.dll!_Button_ReleaseCapture@8()  + 0xd7 байт	
 	comctl32.dll!_Button_WndProc@16()  + 0x887 байт	
 	user32.dll!_InternalCallWinProc@20()  + 0x28 байт	
 	user32.dll!_UserCallWinProcCheckWow@32()  + 0xb7 байт	
 	user32.dll!_DispatchMessageWorker@8()  + 0xdc байт	
 	user32.dll!_DispatchMessageW@4()  + 0xf байт	
 	user32.dll!_IsDialogMessageW@8()  + 0xdb байт	
 	mir_app.mir!mir_main(wchar_t * cmdLine)  Строка 326 + 0xc байт	C++
 	Miranda32.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, wchar_t * cmdLine, HINSTANCE__ * __formal)  Строка 65 + 0x5 байт	C++
 	Miranda32.exe!__tmainCRTStartup()  Строка 547 + 0x1c байт	C
 	kernel32.dll!_BaseProcessStart@4()  + 0x23 байт	

```
	___
	
disasm:	
```

13D79399  lea         edi,[edi]  
13D793A0  push        ebx  
13D793A1  mov         ecx,dword ptr [esp+8]  
13D793A5  mov         eax,0FFFFFFFFh  
13D793AA  mov         edx,dword ptr [esp+0Ch]  
13D793AE  cmp         dword ptr [ecx+8BCh],edx  
13D793B4  mov         ebx,dword ptr [ecx+8B8h]  
13D793BA  jbe         13D793CD  
13D793BC  imul        edx,edx,9918h  
13D793C2  add         edx,ebx  
13D793C4  cmp         byte ptr [edx+34h],0  
13D793C8  je          13D793CD  
13D793CA  mov         eax,dword ptr [edx+20h]  
13D793CD  pop         ebx  
13D793CE  ret  
13D793CF  nop  
13D793D0  push        esi  
13D793D1  push        ebx  
13D793D2  sub         esp,24h  
13D793D5  mov         esi,dword ptr [esp+30h]  
13D793D9  mov         ebx,dword ptr [esp+34h]  
> 13D793DD  mov         eax,dword ptr [esi+8]  
13D793E0  mov         dword ptr [esp],ebx  
13D793E3  add         esi,24h  
13D793E6  add         eax,20h  
13D793E9  mov         dword ptr [esp+4],eax  
13D793ED  call        13DA0A00  
13D793F2  mov         dword ptr [esp],esi  
13D793F5  call        13D6F690  
13D793FA  mov         dword ptr [ebx+20h],eax  
13D793FD  xor         eax,eax  
13D793FF  xor         edx,edx  

```

(esp=1240752)
(esi=0)
(eax=1240960)
(ebx=1240960)
(edx=2090328436)

**Comment by LittleVulpix** [comment]
Strange, I thought this was fixed in https://github.com/miranda-ng/miranda-ng/issues/684 Resurfaced bug I guess?

**Comment by Corak667** [comment]
Very close but still not fixed. In yours issue it's calling Tox.dll plugin, but now it crashes on libtox.dll, so it's a bit another problem.  Importing profile normally, but then it always crashes.

**Comment by aunsane** [comment]
very old and rare crash. won't be fixed
