### ISSUE TITLE
Facebook emojis don't work when picked from the list

### ISSUE THREAD

**Issue by culinko** [miranda-ng/miranda-ng#918]
### Expected behavior
Emoji being displayed

### Actual behavior
An empty square is being displayed

### Does it work in stable version?
I started using SmileyAdd with Facebook_full for the first time, so unfortunately no previous experience to compare to.

### Steps to reproduce that behavior
After my contact picks an emoji from the Facebook's list of emojis (he told me he was on mobile), the emoji won't be displayed and instead it will display a blank square. If he types it manually as ":D", the emoji will be displayed properly. TabSRMM, History++ and Tipper are all affected. The image below shows the comparison for the 2 messages from History++, the first one is where he picked the emoji from the list on mobile, the second is the message where he manually typed ":D" (also on mobile). I don't know if the same issue arises when the sender is on desktop. The Facebook website displays both messages with the emoji that I added on the right, so Miranda should be using the same image from the second message also in the first one.

![emoji](https://user-images.githubusercontent.com/11700272/30141659-17c7a70c-937d-11e7-919c-532a6e4b6adc.png)

When I was searching if this issue has already been reported, I stumbled upon #852 but I don't think it's the same issue since that one seems to be specific to TabSRMM and Windows 10. Thanks for looking into this, much appreciated!

```
CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz [Intel64 Family 6 Model 69 Stepping 1] [DEP Enabled] [4 CPUs]
Installed RAM: 3980 MBytes
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18762 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | English/Slovak
Free disk space on Miranda partition: 61036 MBytes

Miranda NG Version: 0.95.7 alpha build #18489 (e7179d7) x64
Build time: 6 Sep 2017 19:24:44
Profile: C:\Users\culinko\AppData\Roaming\Miranda NG\Profiles\culinko\culinko.dat (dbx mmap driver)
Profile size: 17563648 Bytes
Profile creation date: 23 Aug 2017 9:52:47
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (21):[/b]
¤ AdvaImg.dll v.[b]0.11.0.2[/b] [27 Aug 2017 23:05:16] - Miranda image services 
¤ AVS.dll v.[b]0.95.3.4[/b] [5 Sep 2017 22:52:40] - Avatar service 
¤ Clist_modern.dll v.[b]0.9.1.7[/b] [5 Sep 2017 22:53:02] - Modern contact list 
¤ CrashDumper.dll v.[b]0.0.5.2[/b] [6 Sep 2017 18:25:09] - Crash dumper 
¤ DbEditorPP.dll v.[b]4.0.1.1[/b] [22 Aug 2017 14:31:26] - Database editor++ 
¤ Dbx_mmap.dll v.[b]0.95.3.1[/b] [6 Sep 2017 19:24:46] - Miranda NG mmap database driver 
¤ Facebook.dll v.[b]0.3.3.2[/b] [27 Aug 2017 23:04:46] - Facebook RM 
¤ HistoryPP.dll v.[b]1.5.1.5[/b] [28 Jun 2017 14:22:12] - History++ 
¤ ICQ.dll v.[b]0.11.3.5[/b] [27 Aug 2017 23:04:24] - IcqOscarJ protocol 
¤ Import.dll v.[b]0.95.4.3[/b] [22 Aug 2017 14:29:28] - Import contacts and messages 
¤ MSN.dll v.[b]0.14.0.1[/b] [22 Aug 2017 14:30:06] - MSN protocol 
¤ MyDetails.dll v.[b]0.0.1.12[/b] [22 Aug 2017 14:31:30] - My details 
¤ PluginUpdater.dll v.[b]0.1.2.5[/b] [25 Aug 2017 10:04:08] - Plugin updater 
¤ QuickContacts.dll v.[b]1.0.0.0[/b] [22 Aug 2017 14:31:52] - Quick contacts 
¤ SeenPlugin.dll v.[b]5.0.5.3[/b] [22 Aug 2017 14:30:28] - Last seen 
¤ SmileyAdd.dll v.[b]0.2.4.1[/b] [31 Aug 2017 12:28:06] - SmileyAdd 
¤ StatusManager.dll v.[b]0.11.2.0[/b] [27 Aug 2017 23:05:26] - Status manager 
¤ TabSRMM.dll v.[b]3.5.0.6[/b] [5 Sep 2017 14:27:18] - TabSRMM 
¤ Tipper.dll v.[b]2.1.0.7[/b] [22 Aug 2017 14:30:32] - Tipper 
¤ TopToolBar.dll v.[b]0.8.0.4[/b] [22 Aug 2017 14:31:02] - TopToolBar 
¤ UInfoEx.dll v.[b]0.8.5.0[/b] [22 Aug 2017 14:30:50] - User info ext 

[b]Unloadable Plugins (1):[/b]
¤ DbChecker.dll v.[b]0.0.0.0[/b] [6 Sep 2017 19:25:12] - <unknown> 


[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 1 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
MSN                      0 - Enabled 1 - Disabled  Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [29 Jun 2017 4:08:02]
 Proto_Conn.dll [8 Sep 2005 11:03:16]
 Proto_Facebook.dll [27 Aug 2017 23:04:38]
 Proto_ICQ.dll [27 Aug 2017 23:04:38]
 Proto_MetaContacts.dll [6 Sep 2017 19:26:36]
 Proto_MSN.dll [22 Aug 2017 14:31:04]
 TabSRMM_icons.dll [5 Sep 2017 14:29:00]
 Toolbar_icons.dll [5 Sep 2017 22:54:24]
 UInfoEx_icons.dll [22 Aug 2017 14:30:46]
 xStatus_ICQ.dll [27 Aug 2017 23:04:16]
 xStatus_Jabber.dll [2 May 2015 5:47:06]
```

**Comment by dartraiden** [comment]
Please see note in [https://wiki.miranda-ng.org/index.php?title=Plugin:SmileyAdd/en](our wiki).

**Comment by culinko** [comment]
I'm on Windows 7 Ultimate 64-bit as can be seen in the Version Information I pasted...

**Comment by Robyer** [comment]
It's possible that this is smileypack issue. Try to use this one: https://www.miranda-ng.org/distr/addons/Smileys/facebook_emoji.zip

**Comment by culinko** [comment]
Can confirm that these work, thanks a lot! Will be using the 16x16 ones from now on, I think I even like these more.

So now we know that it's an issue with the smileypack (I got it from https://wiki.miranda-ng.org/index.php?title=Plugin:Facebook/en).

**Comment by Robyer** [comment]
Thanks for info. I updated some links on wiki to point to this working smileypack. But someone (@dartraiden ?) please fix the links in right block, as I ******* hate working with this wiki, it's always driving me crazy 😡

**Comment by dartraiden** [comment]
Done, [Template:PluginInfo ](https://wiki.miranda-ng.org/index.php?title=Template:PluginInfo)

**Comment by Robyer** [comment]
@dartraiden Thanks. Wouldn't make more sense if the text would be directly in [Plugin:Facebook](https://wiki.miranda-ng.org/index.php?title=Plugin:Facebook) (without language part) and not everything in Template:PluginInfo? Also, how do you know what templates contribute to some particular wiki page? (e.g. I want to edit some plugin, how do you find it takes texts from Template:PluginInfo?)

**Comment by Robyer** [comment]
@dartraiden Btw [Plugin:Facebook](https://wiki.miranda-ng.org/index.php?title=Plugin:Facebook) (without language part) still shows old links in the right panel.

**Comment by dartraiden** [comment]
I do not know if our wiki-templates support this. Better ask Goraf.

I remembered how Goraf [removed OpenSSL links](https://wiki.miranda-ng.org/index.php?title=Template:PluginInfo&curid=1095&diff=19854&oldid=19816) from plugin card.

Also, our wiki has some [HowTo](https://wiki.miranda-ng.org/index.php?title=Category:Howto) (for example, [this](https://wiki.miranda-ng.org/index.php?title=Help:Howto/Move_plugin_to_deprecated) HowTo mentions all plugins-related templates.

Finally, if there is no idea where to look, you can use [AutoWikiBrowser](https://sourceforge.net/projects/autowikibrowser/). For example, if you want to find all links to the Trac:

- go to Preferences -> Site and point our wiki as custom Project
- create a list of pages on which to search. Source: category (recursive). Category: Root (it's root category on our wiki) -> Make list
- check "Find and replace option" -> Normal settings. "Find" is "trac.miranda-ng.org" (what you want to find), Replace with is not necessarily because we do not want to automatically replace, so set something like 123. Also, check "Slip if no replacement" option.
- Push the "Start" button. When AWB found an exact match it stops process and you can open the page in a browser for editing. After editing you can push "Skip" button and AWB  will continue to process the remaining pages.

**Comment by dartraiden** [comment]
> Btw Plugin:Facebook (without language part) still shows old links in the right panel.

Make a null edit (just open the edit and immediately save the page without changes). It's caching.
